[toolchain]
package_manager = "yarn"
version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vesting = "5wyZo4T5KuHZzFNFjZrBQTLgKK4CYKyMJ3Rq9HMUZJnF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "vitest"
